modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker_URL}"

[[mods]]
    modId="${mod_id}"
    displayName="${mod_name}"
    description='''${mod_description}'''
    version="${mod_version}"
    authors="${mod_authors}"
    logoFile="${mod_icon}"
    logoBlur=false
    displayURL="${mod_homepage_URL}"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId = "curios"
    mandatory = false
    versionRange ="${curios_version}"

[modproperties.${mod_id}]
    catalogueImageIcon="${mod_icon}"
